version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GIT_0704Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
- name: SIQAJDBCAdapterTests
  version: "1.0"
  gitServerName: SIQAGitHub
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
- name: DADA_GlobalVariable1
  version: "1.0"
  gitServerName: SIQAGitHub
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
- name: SIQACloudStreamsTests
  version: "1.0"
  gitServerName: SIQAGitHub
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
services:
- serviceName: project.siqa_git_0704.integrations:Sum
  packages:
  - name: SIQA_GIT_0704Project
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 12.0.0.0.17
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 12.1.0.0.810
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 12.1.0.0.810
- serviceName: project.siqa_git_0704.integrations:deepclonetest
  packages:
  - name: SIQA_GIT_0704Project
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 12.0.0.0.17
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 12.1.0.0.810
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 12.1.0.0.810
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 12.1.0.0.810
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 12.1.0.0.810
